config/routes.rb
Rails.application.routes.draw do
  root 'session#home'

  post '/register', to: 'user#create'
  post '/login', to: 'session#login'
  post '/publish-post', to: 'post#publish'
  post '/delete-post', to: 'post#delete'
  post '/like-post', to: 'post#like'
  post '/unlike-post', to: 'post#unlike'
  post '/publish-comment', to: 'comment#publish'
  post '/delete-comment', to: 'comment#delete'
  post '/search', to: 'post#search'
  post '/edit-post', to: 'post#edit'

  get '/all-posts', to: 'post#list'
  get '/all-comments/:title', to: 'comment#list'
  
end

app/models/user.rb
class User < ApplicationRecord
    validates :username, presence: true, uniqueness: true, length: {minimum: 5, maximum: 30}
    validates :password, presence: true
end

app/controllers/user_controller.rb
class UserController < ApplicationController
    skip_before_action :verify_authenticity_token, only: [:create]

    def list
        @users = User.all
    end

    def new
        @user = User.new
    end

    def create
      @user = User.new(user_params)

      if check_user_existence
        render json: { error: 'Username already taken' }, status: :unprocessable_entity
      else
        if @user.save
          session[:user_id] = @user_id
          render json: { message: 'User successfully created' }, status: :created
        else
          render json: { error: 'User creation failed:', errors: @user.errors.full_messages }, status: :unprocessable_entity
        end
      end

    end
    


    private

    def check_user_existence
        User.exists?(username: user_params[:username])
    end

    def user_params
        params.require(:user).permit(:username, :password)
    end

    def user_summary(user)
      { username: user.username, password: user.password }
    end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/new.html.erb
<!-- app/views/user/new.html.erb -->

<h1>New User Registration</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="actions">
    <%= f.submit 'Create User' %>
  </div>
<% end %>

<%= link_to 'Back', user_list_path %>